"""Add traceroute hops with location

Revision ID: dbe4a5a106e4
Revises: b15f784b8574
Create Date: 2025-05-17 21:36:44.847463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe4a5a106e4'
down_revision = 'b15f784b8574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traceroute_output', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('traceroute_hops_with_location', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.drop_column('traceroute_hops_with_location')
        batch_op.drop_column('traceroute_output')

    # ### end Alembic commands ###
